### ISSUE TITLE
Add ability to enter xpubs / BIP32 paths as text when creating a new vault.

### ISSUE THREAD

**Issue by Bosch-0** [Lily-Technologies/lily-wallet#16]
It would be handy if you could add your xpubs / BIP32 paths manually as text when creating a wallet.

**Comment by bjarnemagnussen** [comment]
Although probably already known, I just wanted to add that it may also be a good idea to allow optionally adding the fingerprint of the root master key. This is useful since Coldcard when setup with multisig will check for it and don't accept any fingerprints relative to the xpub instead of root master key, see e.g. https://github.com/spesmilo/electrum/issues/5955.

**Comment by KayBeSee** [comment]
Added in 7aba68253bf42011131b12e649c106771d93418f
