### ISSUE TITLE
Legacy transactions with HW wallets

### ISSUE THREAD

**Issue by djpnewton** [Lily-Technologies/lily-wallet#30]
When connecting to a HW wallet should we scan for legacy (non segwit) transactions?

At the moment this is not supported which is probably a bit disconcerting to see "0 balance" on a HW wallet that the user is expecting to have a balance

I imagine it would be relatively simple to show the legacy balance/transactions (add the extra bip32 derivation paths during the scanning phase and plug them into the blockchain utxo/tx search)

**Comment by KayBeSee** [comment]
It should show P2SH(P2WPKH) transactions, which is what Ledger Live and Trezor Wallet use.

If the user setup using Electron with some different setup then it won't show up.

I am hesitant to support additional address types because it adds complexity to the sending process which already branches in three different directions depending on the setup (software wallet / single hardware wallet / multisig vault)

**Comment by djpnewton** [comment]
ledger and trezor use them now by default but if you have an older wallet it can be a legacy type.

also ledger and trezor use bip44 accounts (https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery)

what if we:
 - re-architect a bit to separate out from the UI some sort of a wallet controller
 - bump the file version and add account index to the wallet
 - actively use the addressType and (new) accountIndex fields from the wallet to derive keys and guide spending process

then we could do cool stuff like a cli tool and sweeping from legacy wallets etc, but perhaps still keep the UI from getting cluttered with too many options

I have been playing around with some of these ideas, let me know what you think?
