### ISSUE TITLE
Comparing the perfomance between Blockstream REST API and ElectrumX

### ISSUE THREAD

**Issue by leonardojobim** [Lily-Technologies/lily-wallet#5]
For the purpose of comparing the perfomance between Blockstream REST API and ElectrumX, I rewrote the transactions.js file to connect to any ElectrumX server (using sockets instead of HTTP). I used the ElectrumX client from Blue Wallet.
There is apparently a significant improvement in performance.

I also created a file called transactions_with_full_scan.js, that scan for the transactions, until find a 30 sequential unused addresses. However this limit is parametrized and can be changed.

If interested, the files can be checked and tested at https://github.com/0xLeos/electrumx_perfomance_test

**Comment by KayBeSee** [comment]
Very cool. I have had correctly scanning transactions with a gap limit on the back-burner since the initial release because I didn't think people would hit over 30 transactions before I could fix it. I just incorporated some of your code into one of the latest commits.

I want to look more into ElectrumX. I eventually want people to connect via their own full node or connection information (and not rely on Blockstream API). If using ElectrumX improves initial load time, then I'm all about it.

Do you mind sending me an email by the way (KayBeSee@gmail.com)? I'd like to acknowledge your contributions in the next release.
